name: Deploy Oracle Changes with Liquibase

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-to-oracle:
    name: Deploy to Oracle DB
    runs-on: self-hosted

    steps:
      - name: 1. Check out repository code
        uses: actions/checkout@v4

      - name: 2. Download and Unpack Liquibase
        run: |
          wget -qO- "https://github.com/liquibase/liquibase/releases/download/v4.29.0/liquibase-4.29.0.tar.gz" | tar -xvz
          echo "$PWD/liquibase-4.29.0" >> $GITHUB_PATH

      - name: 3. Run Liquibase Update
        env:
          # Inject secrets as environment variables for liquibase.properties to use
          ORACLE_USER: ${{ secrets.ORACLE_USER }}
          ORACLE_PASSWORD: ${{ secrets.ORACLE_PASSWORD }}
          ORACLE_CONN_STRING: ${{ secrets.ORACLE_CONN_STRING }}
        run: liquibase update
